### PR TITLE
Simplify .travis.yml

### PR DESCRIPTION
**Pull request by lowks**
Simplify `.travis.yml`

### CODE REVIEW

**Comment by danmcclain** [comment]
@rrrene Is there a need to use that specific version of Elixir for inch?

**Comment by lowks** [comment]
Don't think so ... https://github.com/rrrene/inch_ex/blob/master/mix.exs#L8

**Comment by rrrene** [comment]
@danmcclain No, @lowks is right. InchEx should not be restricted to any specific version above 1.0.

That said, if you encounter problems with say Elixir 1.1.X it might very well be InchEx's fault since it is, much like Elixir, still maturing :+1:

**Comment by danmcclain** [comment]
@lowks can you squash your commits? Thanks!

@rrrene thanks for confirming

**Comment by lowks** [comment]
Kindly re-run the test. This failure to install elixir via kiex is a known issue. I fixed it by taking off the line `sudo: false`. Somehow their container infra is still not that stable yet and will periodically fail.

**Comment by danmcclain** [comment]
@lowks Would you mind squashing your commits? Would like to apply this as one commit. Thank you

**Pull request closed without merging**
